name = "PowerModelsONM"
uuid = "25264005-a304-4053-a338-565045d392ac"
authors = ["David M Fobes <dfobes@lanl.gov>"]
version = "1.0.0"

[deps]
Alpine = "07493b3f-dabb-5b16-a503-4139292d7dd4"
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
JSONSchema = "7d188eb4-7ad8-530c-ae41-71a32a6d4692"
JuMP = "4076af6c-e467-56ae-b986-b466b2749572"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
PowerModelsProtection = "719c1aef-945b-435a-a240-4c2992e5e0df"
PowerModelsStability = "f9e4c324-c3b6-4bca-9c3d-419775f0bd17"
ProgressMeter = "92933f4c-e287-5a05-a399-4b506db050ca"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
Alpine = "~0.2.5"
ArgParse = "~1.1"
Cbc = "~0.8.0"
InfrastructureModels = "~0.6"
Ipopt = "~0.6"
JSON = "~0.21"
JSONSchema = "~0.3.3"
JuMP = "~0.21.8"
Juniper = "~0.7"
LoggingExtras = "~0.4.7"
PackageCompiler = "~1.2.6"
PowerModelsDistribution = "~0.11.4"
PowerModelsProtection = "~0.3"
PowerModelsStability = "~0.2.1"
ProgressMeter = "~1.7.1"
Requires = "~1.1.3"
julia = "^1.3"

[extras]
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "JSON", "PowerModelsDistribution"]
