name = "PowerModelsONM"
uuid = "25264005-a304-4053-a338-565045d392ac"
authors = ["David M Fobes <dfobes@lanl.gov>"]
version = "0.4.0"

[deps]
ArgParse = "c7e460c6-2fb9-53a9-8c5b-16f535851c63"
Cbc = "9961bab8-2fa3-5c5a-9d89-47fab24efd76"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Gurobi = "2e9cd046-0924-5485-92f1-d5272153d98b"
InfrastructureModels = "2030c09a-7f63-5d83-885d-db604e0e9cc0"
Ipopt = "b6b21f68-93f8-5de0-b562-5493be1d77c9"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
Juniper = "2ddba703-00a4-53a7-87a5-e8b9971dde84"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
Memento = "f28f55f0-a522-5efc-85c2-fe41dfb9b2d9"
PackageCompiler = "9b87118b-4619-50d2-8e1e-99f35a4d4d9d"
PowerModelsDistribution = "d7431456-977f-11e9-2de3-97ff7677985e"
PowerModelsProtection = "719c1aef-945b-435a-a240-4c2992e5e0df"
PowerModelsStability = "f9e4c324-c3b6-4bca-9c3d-419775f0bd17"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
XLSX = "fdbf4ff8-1666-58a4-91e7-1b58723a45e0"

[compat]
ArgParse = "~1.1"
Cbc = "~0.7.1"
DataFrames = "~0.22"
Gurobi = "~0.9.10"
InfrastructureModels = "~0.5.3"
Ipopt = ">= 0.4"
JSON = "~0.21"
Juniper = "~0.7"
LoggingExtras = "~0.4.5"
Memento = "~1"
PackageCompiler = "~1.2.4"
PowerModelsDistribution = "~0.10.2"
PowerModelsProtection = "~0.2"
PowerModelsStability = "~0.1"
XLSX = "~0.7.6"
julia = "^1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
