#  name: ONM Integration Tests
#  
#  on: push
#  
#  jobs:
#    Ubuntu:
#      name: Test OMF on Ubuntu
#      runs-on: ubuntu-18.04
#      timeout-minutes: 120
#      steps:
#        - uses: actions/checkout@v2 # Checkout whichever ref that triggered this workflow
#        - name: Install Dependencies
#          run: sudo apt install python3
#        - name: Run Tests
#          run: sudo python3 __init__.py
#  macOS:
#    name: Test on macOS
#    runs-on: macos-latest
#    steps:
#      - uses: actions/checkout@v2
#      - name: Install dependencies
#        run: |
#          brew link --overwrite python@3.8
#      - name: Run tests
#        run: |
#          python3 __init__.py